### ISSUE TITLE
Insecure encryption

### ISSUE THREAD

**Issue by GregoryConrad** [D4stiny/jWARE#1]
```
    Cipher aesCIPHER = Cipher.getInstance("AES");
    Key cryptKey = new SecretKeySpec(passKey.getBytes(), "AES");
```

FYI, this by default uses 128-bit AES in ECB mode which can be far more easily broken when encrypting multiple blocks (which would be the case since this ransomware encrypts a user's personal files).

Suggested fix: use http://commons.apache.org/proper/commons-crypto/ and use something like CTR mode with a good IV.

**Comment by D4stiny** [comment]
We're not protecting military secrets here, and good luck cracking AES-128 even if in ECB mode. The key is randomly generated, lower/upper case with numbers. If we were using dictionary words, there could be an issue, however since the password is randomly generated, dictionary attacks would not work, only brute-force would. According to [this study](http://www.eetimes.com/document.asp?doc_id=1279619), it would take 1 billion billion years to crack AES with a key size of 128-bits (brute-forcing).

Another reason I am going with AES-128, rather than AES-256 is because AES-256 requires users to install additional security libraries due to default Java libraries unable to support them. I don't want users of the software to have to install extra libraries in order to use the software, so AES-256 is not viable. See [this](https://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters) for more info.

I do not want to use third-party libraries due to the fact that one of the goals of the project is to use default libraries only. Therefore I am going to close this issue due to the reasons listed.

**Comment by GregoryConrad** [comment]
I'm aware that 256 bit AES is unfeasible. While making my app, I ran into
the same issue. I also don't have an issue with 128-bit AES, as I use it in
my project as well. What I have an issue with is that you are using ECB
with no IV (since you can't with ECB). See
https://crypto.stackexchange.com/a/20946 for why ECB should not be used in
your situation.

Also, for the key (which is relatively secure), you may want to use pbkdf2
(just if you want to take the extra mile).

On Jun 15, 2017 22:14, "Bill Demirkapi" <notifications@github.com> wrote:

We're not protecting military secrets here, and good luck cracking AES-128
even if in ECB mode. The key is randomly generated, lower/upper case with
numbers. If we were using dictionary words, there could be an issue,
however since the password is randomly generated, dictionary attacks would
not work, only brute-force would. According to this study
<http://www.eetimes.com/document.asp?doc_id=1279619>, it would take 1
billion billion years to crack AES with a key size of 128-bits.

Another reason I am going with AES-128, rather than AES-256 is because
AES-256 requires users to install additional security libraries due to
default Java libraries unable to support them. We don't want users of the
software to have to install extra libraries to their testing sessions in
order to use the software, so AES-256 is not viable. See this
<https://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters>
for more info.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/D4stiny/jWARE/issues/1#issuecomment-308912914>, or mute
the thread

**Comment by D4stiny** [comment]
Like I said, we're not protecting military secrets. This vulnerability also requires there are multiple copies of the same block encrypted with ECB. Users are probably not going to have multiple copies of files, even if they do, they can only recover a few files.
